language: r
sudo: false
latex: false
pandoc: false

before_install:
  - git config --global user.email "ztc.ustcer@gmail.com"
  - git config --global user.name "TC"
  - git submodule update --remote

script:
  - Rscript R/aaa.R

after_success:
  - git add --all *
  - git commit -m"Daily update"
  - git push -q https://${GITHUB_PAT}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:master
