baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "asdfasdf"
theme = "docdock"
themesdir = "themes"

[params]
editURL = "https://github.com/vjeantet/hugo-theme-docdock/edit/master/exampleSite/content/"
showVisitedLinks = false # default is false
themeStyle = "original" # "original" or "flex" # default "original"
themeVariant = "blue" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = true # set true to hide next/prev chevron, default is false

[outputs]
home = [ "HTML", "RSS", "JSON"]

